### ISSUE TITLE
Make the API similar to Google Drive

### ISSUE THREAD

**Issue by photopea** [dropbox/dropbox-api-spec#3]
Hi, I am the author of image editor www.Photopea.com .

Some of my [users would like](https://github.com/photopea/photopea/issues/17) my editor to open and save files to their Dropbox accounts. I have already implemented the [Google Drive API](https://www.youtube.com/watch?v=p7kjmwhlNrA). 

When you design your API, can you just copy some existing API (e.g. the one of Google Drive) instead of inventing your own API? Then, it would be enough just to replace the domain name for all API calls.

Implementing new APIs is a very time-consuming process, the hardest part of which is studying the API. If your API was the same as those of others, more developers would connect their apps with Dropbox.

**Comment by greg-db** [comment]
Thanks for the request! We certainly understand that implementing an API can be time-consuming. I'll send this feature request along to the team, but it's unlikely that it will be implemented. The Dropbox API is built to match the specific features available in the Dropbox product itself, which will vary from other products.

Thanks again for taking the time to write this up. If you run in to any issues with the Dropbox API, please let us know and we'll be happy to help.

**Comment by photopea** [comment]
"The Dropbox API is built to match the specific features available in the Dropbox product itself" - I think these features are very similar to features of a Google Drive or other related services. Maybe you could cooperate with Google on creating a common standard for this (like FTP or GIT or something).
