### ISSUE TITLE
list_folder_continue: path_display doesn't respect capital letter in path for FileMetadata object

### ISSUE THREAD

**Issue by khurshid-alam** [dropbox/dropbox-api-spec#4]
Hi I am using webhook and then calling `list_folder_continue` to get modified data. However path_display is different for Foldermetadata and FileMetada for each entry.

```python

dbx = dropbox.Dropbox(token)
result = dbx.files_list_folder_continue(cursor)

for entry in result.entries:
    print (entry)
    if (isinstance(entry, FolderMetadata)):
        print (entry.path_display)   
    
    if (isinstance(entry, FileMetadata)):                
        print (entry.path_display)
```

Lets say I uploaded a folder to Documents/Test/ which contains a test.txt file

```
Documents
    Test
        test.txt

```
The output of above is:
`FolderMetadata(name='Test', id='id:7KpyMyVCGTAAAAAAAAAAGg', path_lower='/documents/test', path_display='/Documents/Test', parent_shared_folder_id='1189873249')`

`FileMetadata(name='test.txt', id='id:7KpyMyVCGTAAAAAAAAAAGg', path_lower='/documents/test/test.txt', path_display='/Documents/test/test.txt')`

Notice how `path_display` is returning folder `test` and not `Test` for FileMetadata. According to v2 api `path_display `should respect capital letter in folder name.

**Comment by greg-db** [comment]
Thanks for writing this up! Unfortunately, this behavior is sometimes expected. Even in `path_display`, the original casing isn't always available. There's a note about this in [the API v2 documentation](https://www.dropbox.com/developers/documentation/http/documentation), under "Case insensitivity": 
> Also, while Dropbox is case-insensitive, it makes efforts to be case-preserving. Metadata.name will contain the correct case. Metadata.path_display usually will contain the correct case, but sometimes only in the last path component. If your app needs the correct case for all components, it can get it from the Metadata.name or last path component of each relevant Metadata.path_display entry.

We understand this is non-ideal of course, and I'll forward this on to the team as feedback, but I can't make any promises as to if or when this might be improved in the future.

**Comment by khurshid-alam** [comment]
Ah right. Thanks for the explanation.
