### ISSUE TITLE
Is there a json or yaml format of the Dropbox OpenAPI spec? Can I generate either a json or yaml file from the contents of this repo if not?

### ISSUE THREAD

**Issue by bjonesy** [dropbox/dropbox-api-spec#63]
Was hoping to find a json or yaml file for the Dropbox OPenAPI spec in this repo. Similar to this https://github.com/APIs-guru/openapi-directory/blob/main/APIs/box.com/2.0.0/openapi.yaml. Can I generate a json or yaml file using the contents in this repo? Are there already generated files that exist somewhere that someone could point me to?

**Comment by bjonesy** [comment]
I guess this is what I need in order to generate a json file I can use to then convert to yaml. Before I close this ticket is this correct? https://github.com/dropbox/stone. In my opinion it would still be useful to have a reference to an already generated OpenAPI json or yaml spec file.

**Comment by greg-db** [comment]
Dropbox does not offer an OpenAPI specification of the Dropbox API, but I'll pass this along as a feature request. I can't promise if or when that might be implemented though. For reference, yes, this Dropbox API spec is written in [Stone](https://github.com/dropbox/stone/).

You can find [the license that dictates what you may do with this spec here](https://github.com/dropbox/dropbox-api-spec/blob/main/LICENSE). Likewise, [the license for the Stone project can be found here](https://github.com/dropbox/stone/blob/main/LICENSE).

**Comment by bjonesy** [comment]
Thanks @greg-db. Appreciate the quick response.
